# Generated by Django 3.0.6 on 2020-06-11 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=50)),
                ('trainer', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Experience Information',
            },
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Government', 'Government'), ('Non-Government', 'Non-Government')], max_length=50)),
                ('joining_date', models.DateField()),
                ('institute_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Department')),
                ('job_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Designation')),
            ],
            options={
                'verbose_name_plural': 'Job Information',
            },
        ),
        migrations.CreateModel(
            name='TrainingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Training Information',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='teacher_photos/')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('religion', models.CharField(choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Other', 'Other')], max_length=50)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Single', 'Single')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.ExperienceInfo')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.JobInfo')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.TrainingInfo')),
            ],
            options={
                'verbose_name_plural': 'Personal Information',
            },
        ),
    ]
