# Generated by Django 3.0.6 on 2020-07-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200731_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='photo',
            field=models.ImageField(blank=True, default='teacher_photos/defaultuser.png', null=True, upload_to='teacher_photos/'),
        ),
    ]
