# Generated by Django 3.0.6 on 2020-06-11 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=15, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'ClassInfo',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(choices=[('Science Department', 'Science Department'), ('Math Department', 'Math Department'), ('English Department', 'English Department'), ('Kiswahili Department', 'Kiswahili Department'), ('CRE Department', 'CRE Department'), ('Social-Studies Department', 'Social-Studies Department')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('classinfo', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.ClassInfo')),
            ],
            options={
                'verbose_name_plural': 'ClassRegistration',
            },
        ),
    ]
