# Generated by Django 3.0.6 on 2020-07-29 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinfo',
            name='capacity',
        ),
    ]
