# Generated by Django 3.0.6 on 2020-06-11 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='parent_photos/')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('religion', models.CharField(choices=[('christian', 'Christian'), ('muslim', 'Muslim'), ('other', 'Other')], max_length=50)),
                ('relationship_to_student', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Guardian', 'Guardian')], default='Mother', max_length=50)),
                ('parent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.PersonalInfo')),
            ],
            options={
                'verbose_name_plural': 'Personal Information',
            },
        ),
    ]
