# Generated by Django 3.0.6 on 2020-07-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
