# Generated by Django 3.0.6 on 2020-07-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_personalinfo_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='parent_to',
            field=models.CharField(max_length=100),
        ),
    ]
