# Generated by Django 3.0.6 on 2020-06-11 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.IntegerField(default=842747, unique=True)),
                ('status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Not Enrolled', 'Not Enrolled')], max_length=20)),
                ('is_in_session', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.ClassInfo')),
            ],
            options={
                'verbose_name_plural': 'Academic Information',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='student_photos/')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('religion', models.CharField(choices=[('christian', 'Christian'), ('muslim', 'Muslim'), ('other', 'Other')], max_length=50)),
                ('birth_certficate_no', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Personal Information',
            },
        ),
        migrations.CreateModel(
            name='EnrolledStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.ClassRegistration')),
                ('name', models.ForeignKey(default='name', null=True, on_delete=django.db.models.deletion.CASCADE, to='student.PersonalInfo')),
                ('student_registration_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.AcademicInfo')),
            ],
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='personalInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.PersonalInfo'),
        ),
    ]
