# Generated by Django 3.0.6 on 2020-06-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='enrolledstudent',
            name='status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Not Enrolled', 'Not Enrolled')], default='Not Enrolled', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=258346, unique=True),
        ),
    ]
