# Generated by Django 3.0.6 on 2020-06-29 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200611_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledstudent',
            name='status',
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Not Enrolled', 'Not Enrolled')], default='Not Enrolled', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='personalInfo',
            field=models.ForeignKey(max_length=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.PersonalInfo'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=199987, unique=True),
        ),
    ]
