# Generated by Django 3.0.6 on 2020-06-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200629_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='birth_certficate_no',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='birth_certificate_no',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=545308, unique=True),
        ),
    ]
