# Generated by Django 3.0.6 on 2020-06-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200629_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=1988, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='birth_certificate_no',
            field=models.IntegerField(default=0),
        ),
    ]
