# Generated by Django 3.0.6 on 2020-06-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200629_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicinfo',
            old_name='is_in_session',
            new_name='is_delete',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=162838, unique=True),
        ),
    ]
