# Generated by Django 3.0.6 on 2020-07-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('student', '0007_auto_20200630_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledstudent',
            old_name='student_registration_number',
            new_name='student',
        ),
        migrations.AddField(
            model_name='enrolledstudent',
            name='roll',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=669711, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='enrolledstudent',
            unique_together={('class_name', 'roll')},
        ),
        migrations.RemoveField(
            model_name='enrolledstudent',
            name='name',
        ),
    ]
