# Generated by Django 3.0.6 on 2020-08-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20200729_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=44719, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student-photos/'),
        ),
    ]
